inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.5
  
Naming/FileName:
  Exclude:
    - 'lib/winrm-fs.rb'

Style/Encoding:
  Enabled: true

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25
